### ISSUE TITLE
problems with tidyverse?

### ISSUE THREAD

**Issue by balima78** [data-cleaning/dcmodify#13]
Hi Mark
I was replicating the code in your vignette("introduction",package="dcmodify") and if I run  library(tidyverse), I will have the error:
> ret1 <- modify(retailers,m)
Error: Can't convert a `modifier` object to function
Run `rlang::last_error()` to see where the error occurred.

if I restart R and just run the libraries 'dcmodify' and 'magrittr', I have no problems

cheers

**Comment by markvanderloo** [comment]
HI Bruno,

This may be a collision with one of the many, many functions that tidyverse
exports. Maybe if you load dcmodify before tidyverse it works? Otherwise,
please send me the complete code (including where you load tidyverse, and
all the output) so I can see if there are any warnings or conflicts.

Cheers,
Mark

**Comment by balima78** [comment]
when I run it this:

library(dcmodify)
library(magrittr)

data("retailers", package="validate")
head(retailers[-(1:2)],3)

m <- modifier(
  if (other.rev < 0) other.rev <- -1 * other.rev
  , if ( is.na(staff.costs) ) staff.costs <- mean(staff.costs)
)

ret1 <- modify(retailers,m)


it works properly, but if I load tidyverse and try it again I have an error:

library(tidyverse)
ret1 <- modify(retailers,m)

> library(tidyverse)
-- Attaching packages ------------------------------------------------------------- tidyverse 1.3.0 --
  v ggplot2 3.3.3     v purrr   0.3.4
v tibble  3.1.0     v dplyr   1.0.5
v tidyr   1.1.3     v stringr 1.4.0
v readr   1.3.1     v forcats 0.5.0
-- Conflicts ---------------------------------------------------------------- tidyverse_conflicts() --
  x tidyr::extract()   masks magrittr::extract()
x dplyr::filter()    masks stats::filter()
x dplyr::lag()       masks stats::lag()
x purrr::modify()    masks dcmodify::modify()
x purrr::set_names() masks magrittr::set_names()
Warning messages:
  1: package ‘tidyverse’ was built under R version 3.6.3 
2: package ‘ggplot2’ was built under R version 3.6.3 
3: package ‘tibble’ was built under R version 3.6.3 
4: package ‘tidyr’ was built under R version 3.6.3 
5: package ‘purrr’ was built under R version 3.6.3 
6: package ‘dplyr’ was built under R version 3.6.3 
7: package ‘forcats’ was built under R version 3.6.3 
> ret1 <- modify(retailers,m)
Error: Can't convert a `modifier` object to function
Run `rlang::last_error()` to see where the error occurred.

**Comment by markvanderloo** [comment]
Ah, there you have it, in the list of conflicts. Apparently `purrr` now also exports a `modify` function. (why didn't they ask me before doing that ;-)).

You can use `dcmodify::modify` to disambiguate between the two.

**Comment by balima78** [comment]
sorry, my bad!

next time I will pay more attention. 

by the way, how can I get access to the supplementary materials from your paper 'Data Validation Infrastructure for R'?
I would like to use  your modifier function with .file or .data, as in your example:

dcmodify::modifier(.file="modifiers.R")

thank you for the patience,

best regards

**Comment by markvanderloo** [comment]
No problem at all. I'll mail you the supplementary files. They will be generally available when jss publishes the paper
